config/routes.rb
Rails.application.routes.draw do

  resources :products
  resources :categories
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]

  namespace :admin do
    resources :products
  end

  devise_for :users, controllers: {
      sessions: 'user/sessions'
  }

  get '/contact' => 'products#contact'

  root 'products#index'
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_and_belongs_to_many :categories
  has_many :order_items
  default_scope { where(active:true) }

  validates :title, :description, :quantity, :price, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0}, :format => { :with => /\A\d+(?:\.\d{0,2})?\z/ }

  validates :quantity, numericality: {greater_than: 0}
  validates :picture, presence: true
  # has_attached_file :picture, styles: { medium: "300x300>", thumb: "100x100>" }
  # validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController

  def index
    @products = Product.all
  end

  def edit
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to admin_products_path
    else
      #errors
      render 'edit'
    end
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:success] = ["Thanks for entering a new product called #{@product.title}"]
      redirect_to admin_products_path
    else
      flash[:error] = @product.errors.full_messages
      render 'new'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:error] = ["You have removed product called, #{@product.title}"]
    redirect_to admin_products_path
  end

  private
    def product_params
     params.require(:product).permit(:title, :description, :price, :quantity, :picture)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @products = Product.all
    @categories = Category.all
    @order_item = current_order.order_items.new
  end

  def show
    @product = Product.find(params[:id])
    @categories = @product.categories
    @order_item = current_order.order_items.new
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:success] = ["Thanks for entering a new product called #{@product.title}"]
      redirect_to @product # same as product_path(@product)
    else
      flash[:error] = @product.errors.full_messages
      render 'new'
    end
  end

  def update
    @product = Product.find(params[:id])
    success = @product.update(product_params)
    if success
      redirect_to product_path(@product)
    else
      render 'edit'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    flash[:error] = ["You have removed product called #{@product.title}"]
    redirect_to root_path
  end

  private
    def product_params
     params.require(:product).permit(:title, :description, :price, :quantity, :picture)
    end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/product_helper.rb
module ProductHelper
  def truncate_if_long(input, max_chars)
    result = input[0..max_chars-1]

    result += '...' if input.length > max_chars

    result
  end
end

app/views/products/_category.html.haml
-category.products.each do |product|
  .col-sm-4.col-lg-4.col-md-4
    .thumbnail
      %img{:alt => "http://placehold.it/320x150", :src => product.picture}
        .caption
          %h4.pull-right $#{product.price}
          %h4
            %a{:href => product_path(product)}=product.title
          %h5
            %a{:href => ""}=product.categories.first.name
          %p=product.description
        .ratings
          %p.pull-right #{rand(1..20)} reviews
          %p
            %span.glyphicon.glyphicon-star
            %span.glyphicon.glyphicon-star
            %span.glyphicon.glyphicon-star
            %span.glyphicon.glyphicon-star
            %span.glyphicon.glyphicon-star

app/views/products/_product_add_to_cart.html.haml
= form_for :order_item, url: order_items_path, remote: true do |f|
  %h4.text-right
    Unit Price:
    %span{:style => "color: green"}= number_to_currency product.price
    .input-group
      = f.number_field :quantity, value: 1, class: "form-control", min: 1
      .input-group-btn.add-cart
        = f.hidden_field :product_id, value: product.id
        = f.submit "Add to Cart", class: "btn btn-primary"

app/views/products/_product_tile.html.haml
.thumbnail
  %img{:alt => "http://placehold.it/320x150", :src => product.picture}
  .caption
    %h4
      %a{:href => product_path(product)}=product.title
    %h5
      %a{:href => "" }=product.categories.first.name
    %p.product-description=truncate_if_long(product.description, 40)

    =render partial: 'products/product_add_to_cart', locals: {product: product}

  .ratings
    %p.pull-right #{rand(1..20)} reviews
    %p
      - rand(1..5).times do
        %span.glyphicon.glyphicon-star

app/views/products/contact.html.haml
.contact-page
  .container
    .col-md-6
      %h1 Contact Us
      %form{:action => "mailto:DBC.Shoppe@gmail.com", :enctype => "text/plain", :method => "GET"}
        .form-group
          %label{:for => "username"} Name:
          %input.form-control{:name => "user[name]", :placeholder => "Enter your name", :type => "text"}
        .form-group
          %label{:for => "email"} Email Address:
          %input.form-control{:name => "user[email]", :placeholder => "Enter your email address", :type => "email"}
        .form-group
          %label{:for => "enquiry"} Enquiry:
          %textarea.form-control{:placeholder => "Please enter your enquiry", :rows => "7"}
        %button.btn.btn-default{:type => "submit"} Submit
    .col-md-6
      %h3.page-header We are here to help
      %p.paragraph
        If you have any enquiries, please feel free to send us via contact service form on the left. You can also send us an email via
        %a{:href => "mailto:DBC.Shoppe@gmail.com?subject=Contacting%20you...&body=Please%20help!!"} contact us.

        Thank you.

app/views/products/edit.html.haml
%h1 Editing product
= form_for :product, url: product_path(@product), method: :patch do |f|
  - if @product.errors.any?
    #error_explanation
      %h2
        = pluralize(@product.errors.count, "error")
        prohibited
        this product from being saved:
      %ul
        - @product.errors.full_messages.each do |msg|
          %li= msg
  %p
    = f.label :title
    %br
      = f.text_field :title
  %p
    = f.label :picture
    %br
      = f.file_field :picture
  %p
    = f.label :description
    %br
      = f.text_area :description
  %p
    = f.label :quantity
    %br
      = f.number_field :quantity
  %p
    = f.label :price
    %br
      = f.number_field :price
  %p
    = f.submit

= link_to 'Back', products_path

app/views/products/index.html.haml
.container.product-index
  .row.carousel-holder
    .col-xs-12
      #carousel-example-generic.carousel.slide{"data-ride" => "carousel"}
        %ol.carousel-indicators
          %li.active{"data-slide-to" => "0", "data-target" => "#carousel-example-generic"}
          %li{"data-slide-to" => "1", "data-target" => "#carousel-example-generic"}
          %li{"data-slide-to" => "2", "data-target" => "#carousel-example-generic"}
        .carousel-inner
          .item.active
            %img.slide-image{src: "https://cdn2.f-cdn.com/contestentries/286246/16249024/561e410f701b8_thumb900.jpg"}
          .item
            %img.slide-image{src: "http://www.arrastheme.xyz/images/blog/team/sales/newyears-banner-blog.jpg"}
          .item
            %img.slide-image{src: "http://hellolennon.com/wp-content/uploads/2015/05/SALE-BANNER.jpg"}
        %a.left.carousel-control{"data-slide" => "prev", href: "#carousel-example-generic"}
          %span.glyphicon.glyphicon-chevron-left
        %a.right.carousel-control{"data-slide" => "next", href: "#carousel-example-generic"}
          %span.glyphicon.glyphicon-chevron-right
  .row.product-list
    - @products.each do |product|
      .col-sm-6.col-md-4.col-lg-3
        = render partial: 'products/product_tile', locals: {product: product}

app/views/products/new.html.haml
= form_for :product, url: products_path do |f|
  - if @product.errors.any?
    #error_explanation
      %h3
        = pluralize(@product.errors.count, "error")
        prevented this product from being saved:
        %br
  %p
    = f.label :title
    %br
      = f.text_field :title
  %p
    = f.label :picture
    %br
      = f.url_field :picture
  %p
    = f.label :description
    %br
      = f.text_area :description
  %p
    = f.label :quantity
    %br
      = f.number_field :quantity
  %p
    = f.label :price
    %br
      = f.number_field :price
  %p
    = f.submit
= link_to 'Back', products_path

app/views/products/show.html.haml
.container
  .row
    .col-md-8.col-md-offset-2
      .thumbnail
        %img.img-responsive{:alt => "http://placehold.it/800x300", :src => @product.picture}
          .caption-full
            %h4
              %a{:href => product_path(@product)}=@product.title
            %p=@product.description
            Stock: #{@product.quantity}
            =render partial: 'product_add_to_cart', locals: {product: @product, order_item: @order_item}
          .ratings
            %p.pull-right 3 reviews
            %p
              %span.glyphicon.glyphicon-star
              %span.glyphicon.glyphicon-star
              %span.glyphicon.glyphicon-star
              %span.glyphicon.glyphicon-star
              %span.glyphicon.glyphicon-star-empty
              4.0 stars
      .well
        .text-right
          %a.btn.btn-success Leave a Review
        %hr
          .row
            .col-md-12
              %span.glyphicon.glyphicon-star
              %span.glyphicon.glyphicon-star
              %span.glyphicon.glyphicon-star
              %span.glyphicon.glyphicon-star
              %span.glyphicon.glyphicon-star-empty
              Anonymous
              %span.pull-right 10 days ago
              %p This product was great in terms of quality. I would definitely buy another!











/ %h2 The product details
/ Title: #{@product.title}
/ %br
/   %img{:src => @product.picture}
/   %br
/     Description: #{@product.description}
/     %br
/       QTY: #{@product.quantity}
/       %br
/         Price: $#{@product.price}

/ = link_to 'Edit', edit_product_path(@product)
/ |
/ = link_to 'Destroy', product_path(@product), method: :delete, data: { confirm: 'Are you sure you want to remove the item'}
/ |
/ = link_to 'Back', products_path